{{- range $scenario, $_ := .Values.servers }}
{{- $server := dict "root" $ "scenario" $scenario }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "augustad.serverName" $server }}
  labels:
    {{- include "augustad.labels" $ | nindent 4 }}
    scenario: {{ $scenario }}
data:
  augustad.yaml: |
    {{- include "augustad.config" $server | nindent 4 }}
{{- end }}
