apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "augustad.fullname" . }}
  labels:
    {{- include "augustad.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "augustad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "augustad.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: augustad
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: game
              containerPort: {{ .Values.service.port }}
              protocol: UDP
          env:
            - name: AUGUSTA_PACK_VERSION
              value: {{ .Values.assetPacks.packVersion | quote }}
          volumeMounts:
            - name: asset-packs
              mountPath: /srv/augusta/asset-packs
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: asset-packs
          hostPath:
            path: {{ .Values.assetPacks.hostPath }}
            type: DirectoryOrCreate
