apiVersion: v1
kind: Service
metadata:
  name: {{ include "augustad.fullname" . }}
  labels:
    {{- include "augustad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "augustad.selectorLabels" . | nindent 4 }}
  ports:
    - name: game
      port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
