{{- range $scenario, $values := .Values.servers }}
{{- $server := dict "root" $ "scenario" $scenario }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "augustad.serverName" $server }}
  labels:
    {{- include "augustad.labels" $ | nindent 4 }}
    scenario: {{ $scenario }}
spec:
  type: {{ $.Values.service.type }}
  selector:
    {{- include "augustad.serverSelectorLabels" $server | nindent 4 }}
  ports:
    - name: game
      port: {{ $.Values.service.port }}
      targetPort: game
      protocol: UDP
      {{- with $values.nodePort }}
      nodePort: {{ . }}
      {{- end }}
{{- end }}
