#!/usr/bin/env bash
# A release's changelog section, generated by git-cliff (cliff.toml) from the
# commits since the previous v* tag. Run on the release/* branch before it is
# merged to main, it prepends the section to CHANGELOG.md for that branch to
# commit; release.yml runs it with --notes on the tag for the GitHub Release.
#
#   scripts/changelog.sh v1.1.0           # prepend v1.1.0 to CHANGELOG.md
#   scripts/changelog.sh v1.1.0 --notes   # print v1.1.0's section alone
set -euo pipefail

version="$1"
mode="${2:-}"

# The previous release is the v* tag sorting just below this version, not the
# nearest one in the history: a tag sits on main's merge commit, which develop,
# and so a release/* branch, never contains.
previous="$({ git tag --list 'v[0-9]*'; echo "$version"; } | sort -uV | grep -B1 -xF "$version" | head -n 1)"
range=()
if [ "$previous" != "$version" ]; then
  range=("$previous..HEAD")
fi

cliff=(uvx git-cliff@2.14.2 "${range[@]}" --tag "$version")
if [ "$mode" = "--notes" ]; then
  "${cliff[@]}" --strip all
elif [ -f CHANGELOG.md ]; then
  "${cliff[@]}" --prepend CHANGELOG.md
else
  "${cliff[@]}" --output CHANGELOG.md
fi
